name: example
description: Example of using the open_weather_map_client package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_weather_map_client:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/lint
  lint: ^1.7.2

flutter:
  uses-material-design: true
